// SPDX-FileCopyrightText: 2025 Capibara Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Capibara.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSPopup : DefaultWindow
{
    public event Action<bool>? OnChoice;

    public TTSPopup()
    {
        RobustXamlLoader.Load(this);

        MessageLabel.SetMessage(Loc.GetString("tts-popup-message"));

        EnableButton.OnPressed += _ =>
        {
            OnChoice?.Invoke(true);
            Close();
        };

        DisableButton.OnPressed += _ =>
        {
            OnChoice?.Invoke(false);
            Close();
        };
    }
}
