// SPDX-FileCopyrightText: 2021 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Watermelon914 <3052169-Watermelon914@users.noreply.gitlab.com>
// SPDX-FileCopyrightText: 2021 Watermelon914 <37270891+Watermelon914@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Vordenburg <114301317+Vordenburg@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 ElectroJr <leonsfriedrich@gmail.com>
// SPDX-FileCopyrightText: 2024 Eoin Mcloughlin <helloworld@eoinrul.es>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 eoineoineoin <github@eoinrul.es>
// SPDX-FileCopyrightText: 2024 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2024 osjarw <62134478+osjarw@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 ShadowCommander <10494922+ShadowCommander@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Starlight.CCVar;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Labels.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HandLabelerWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfg = default!;

        public event Action<string>? OnLabelChanged;
        public event Action<string>? OnLabelSelected;

        /// <summary>
        /// Is the user currently entering text into the control?
        /// </summary>
        private bool _focused;
        // TODO LineEdit Make this a bool on the LineEdit control

        private string _label = string.Empty;
        private string _initialLabel = string.Empty;
        private bool _deleteMode;
        private readonly List<string> _savedLabels = new();

        public HandLabelerWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            LabelLineEdit.OnTextChanged += e =>
            {
                _label = e.Text;
                OnLabelChanged?.Invoke(_label);
                UpdateButtons();
            };

            LabelLineEdit.OnFocusEnter += _ => _focused = true;
            LabelLineEdit.OnFocusExit += _ =>
            {
                _focused = false;
                LabelLineEdit.Text = _label;
            };

            // Capibara - Starlight port: saved labels buttons
            ResetButton.OnPressed += _ =>
            {
                SetCurrentLabel(_initialLabel);
                OnLabelChanged?.Invoke(_initialLabel);
            };

            ClearButton.OnPressed += _ =>
            {
                SetCurrentLabel(string.Empty);
                OnLabelChanged?.Invoke(string.Empty);
            };

            SaveLabelButton.OnPressed += _ =>
            {
                if (string.IsNullOrWhiteSpace(_label))
                    return;

                if (_savedLabels.Contains(_label))
                    return;

                _savedLabels.Add(_label);
                SaveSavedLabelsToCVar();
                UpdateSavedLabels();
                UpdateButtons();
            };

            DeleteLabelButton.OnPressed += _ =>
            {
                _deleteMode = !_deleteMode;
                DeleteLabelButton.Text = _deleteMode
                    ? Loc.GetString("hand-labeler-delete-mode-text")
                    : Loc.GetString("hand-labeler-delete-label-text");
                UpdateButtons();
            };

            SavedLabelsList.OnItemSelected += args =>
            {
                if (args.ItemIndex < 0 || args.ItemIndex >= _savedLabels.Count)
                    return;

                var selectedLabel = _savedLabels[args.ItemIndex];

                if (_deleteMode)
                {
                    _savedLabels.RemoveAt(args.ItemIndex);
                    SaveSavedLabelsToCVar();
                    UpdateSavedLabels();
                    UpdateButtons();
                }
                else
                {
                    OnLabelSelected?.Invoke(selectedLabel);
                }

                SavedLabelsList.ClearSelected();
            };

            LoadSavedLabelsFromCVar();
            UpdateSavedLabels();
            UpdateButtons();
        }

        protected override void Opened()
        {
            base.Opened();

            // Give the editor keyboard focus, since that's the only
            // thing the user will want to be doing with this UI
            LabelLineEdit.GrabKeyboardFocus();
        }

        public void SetCurrentLabel(string label)
        {
            if (label == _label)
                return;

            _label = label;
            if (!_focused)
                LabelLineEdit.Text = label;

            UpdateButtons();
        }

        public void SetMaxLabelLength(int maxLength)
        {
            LabelLineEdit.IsValid = s => s.Length <= maxLength;
        }

        /// <summary>
        /// Captures the current label as the initial state for Reset.
        /// </summary>
        public void SetInitialLabelState()
        {
            _initialLabel = _label;
        }

        private void LoadSavedLabelsFromCVar()
        {
            _savedLabels.Clear();
            var raw = _cfg.GetCVar(StarlightCCVars.HandLabelerSavedLabels);
            if (string.IsNullOrEmpty(raw))
                return;

            foreach (var line in raw.Split('\n'))
            {
                var trimmed = line.Trim();
                if (!string.IsNullOrEmpty(trimmed))
                    _savedLabels.Add(trimmed);
            }
        }

        private void SaveSavedLabelsToCVar()
        {
            var value = string.Join('\n', _savedLabels);
            _cfg.SetCVar(StarlightCCVars.HandLabelerSavedLabels, value);
            _cfg.SaveToFile();
        }

        private void UpdateSavedLabels()
        {
            SavedLabelsList.Clear();
            foreach (var label in _savedLabels)
            {
                SavedLabelsList.AddItem(label);
            }
        }

        private void UpdateButtons()
        {
            SaveLabelButton.Disabled = string.IsNullOrWhiteSpace(_label) || _savedLabels.Contains(_label);
            DeleteLabelButton.Disabled = _savedLabels.Count == 0;

            if (_savedLabels.Count == 0 && _deleteMode)
            {
                _deleteMode = false;
                DeleteLabelButton.Text = Loc.GetString("hand-labeler-delete-label-text");
            }
        }
    }
}
