// SPDX-FileCopyrightText: 2025 Capibara Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Capibara.NanoGigs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Capibara.NanoGigs;

[GenerateTypedNameReferences]
public sealed partial class NanoGigsUiFragment : BoxContainer
{
    public event Action<string, string, string, int>? OnPostJob;
    public event Action<int>? OnAcceptJob;
    public event Action<int>? OnFinishJob;
    public event Action<int>? OnCancelJob;
    public event Action? OnToggleAlerts;

    public NanoGigsUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        TabContainer.SetTabTitle(JobBoardTab, Loc.GetString("nanogigs-ui-tab-board"));
        TabContainer.SetTabTitle(MyJobsTab, Loc.GetString("nanogigs-ui-tab-myjobs"));
        TabContainer.SetTabTitle(PostJobTab, Loc.GetString("nanogigs-ui-tab-post"));

        PayInput.InitDefaultButtons();
        PayInput.IsValid = i => i >= 1;
        PayInput.Value = 50;

        PostButton.OnPressed += _ =>
        {
            var title = TitleInput.Text.Trim();
            var description = DescriptionInput.Text.Trim();
            var location = LocationInput.Text.Trim();
            var pay = PayInput.Value;

            if (string.IsNullOrEmpty(title) || pay <= 0)
                return;

            OnPostJob?.Invoke(title, description, location, pay);

            TitleInput.Text = "";
            DescriptionInput.Text = "";
            LocationInput.Text = "";
            PayInput.Value = 50;
            UpdateCounter(TitleCounter, 0, MaxTitle);
            UpdateCounter(DescriptionCounter, 0, MaxDescription);
            UpdateCounter(LocationCounter, 0, MaxLocation);

            // Switch to My Jobs tab
            Tabs.CurrentTab = 1;
        };

        AbandonButton.OnPressed += _ =>
        {
            if (_activeJobId != null)
                OnCancelJob?.Invoke(_activeJobId.Value);
        };

        AlertsButton.OnToggled += _ => OnToggleAlerts?.Invoke();

        // Character limits — clamp input and update counters
        TitleInput.OnTextChanged += _ => ClampAndCount(TitleInput, TitleCounter, MaxTitle);
        DescriptionInput.OnTextChanged += _ => ClampAndCount(DescriptionInput, DescriptionCounter, MaxDescription);
        LocationInput.OnTextChanged += _ => ClampAndCount(LocationInput, LocationCounter, MaxLocation);
        UpdateCounter(TitleCounter, 0, MaxTitle);
        UpdateCounter(DescriptionCounter, 0, MaxDescription);
        UpdateCounter(LocationCounter, 0, MaxLocation);
    }

    private const int MaxTitle = 50;
    private const int MaxDescription = 150;
    private const int MaxLocation = 50;

    private static void ClampAndCount(LineEdit input, Label counter, int max)
    {
        if (input.Text.Length > max)
        {
            input.Text = input.Text[..max];
            input.CursorPosition = max;
        }

        UpdateCounter(counter, input.Text.Length, max);
    }

    private static void UpdateCounter(Label counter, int len, int max)
    {
        counter.Text = $"{len}/{max}";
        counter.Modulate = len >= max ? Color.FromHex("#e93d58") : Color.FromHex("#888888");
    }

    private int? _activeJobId;

    public void UpdateState(NanoGigsUiState state)
    {
        // Balance + Alerts
        BalanceLabel.Text = Loc.GetString("nanogigs-ui-balance-value", ("balance", state.ViewerBalance));
        AlertsButton.Pressed = state.AlertsEnabled;
        AlertsLabel.Text = state.AlertsEnabled
            ? Loc.GetString("nanogigs-ui-alerts-on")
            : Loc.GetString("nanogigs-ui-alerts-off");
        AlertsLabel.Modulate = state.AlertsEnabled ? Color.FromHex("#3dd425") : Color.FromHex("#888888");

        // Error
        if (!string.IsNullOrEmpty(state.ErrorMessage))
        {
            ErrorPanel.Visible = true;
            ErrorLabel.Text = state.ErrorMessage;
            ErrorLabel.Modulate = Color.FromHex("#e93d58");
        }
        else
        {
            ErrorPanel.Visible = false;
        }

        // Check if viewer has an active job as taker
        var activeJob = state.Jobs.Find(j =>
            j.Status == NanoGigStatus.Accepted && j.TakerAccountId == state.ViewerAccountId);

        _activeJobId = activeJob?.GigId;

        // Job Board tab: show active job view or browse view
        if (activeJob != null)
        {
            BrowseView.Visible = false;
            ActiveJobView.Visible = true;
            PopulateActiveJob(activeJob);
        }
        else
        {
            BrowseView.Visible = true;
            ActiveJobView.Visible = false;
            PopulateJobBoard(state);
        }

        // My Jobs tab
        PopulateMyJobs(state);
    }

    private void PopulateActiveJob(NanoGigListing job)
    {
        ActiveJobTitle.SetMessage(FormattedMessage.FromUnformatted(job.Title));
        ActiveJobDescription.SetMessage(FormattedMessage.FromUnformatted(
            string.IsNullOrEmpty(job.Description)
                ? Loc.GetString("nanogigs-ui-no-description")
                : job.Description));
        ActiveJobLocation.SetMessage(FormattedMessage.FromUnformatted(
            string.IsNullOrEmpty(job.Location)
                ? ""
                : Loc.GetString("nanogigs-ui-location", ("location", job.Location))));
        ActiveJobPoster.SetMessage(FormattedMessage.FromUnformatted(
            Loc.GetString("nanogigs-ui-posted-by", ("name", job.PosterName))));
        ActiveJobPay.Text = Loc.GetString("nanogigs-ui-pay-amount", ("pay", job.Pay));
        ActiveJobPay.Modulate = Color.FromHex("#3dd425");
    }

    private void PopulateJobBoard(NanoGigsUiState state)
    {
        JobListContainer.RemoveAllChildren();

        var availableJobs = state.Jobs.FindAll(j => j.Status == NanoGigStatus.Available);
        EmptyBoardLabel.Visible = availableJobs.Count == 0;

        foreach (var job in availableJobs)
        {
            var listing = new NanoGigsListingControl(job, state.ViewerAccountId, NanoGigsListingMode.Board);
            listing.OnAccept += id => OnAcceptJob?.Invoke(id);
            JobListContainer.AddChild(listing);
        }
    }

    private void PopulateMyJobs(NanoGigsUiState state)
    {
        MyJobsContainer.RemoveAllChildren();

        var myJobs = state.Jobs.FindAll(j => j.PosterAccountId == state.ViewerAccountId);
        EmptyMyJobsLabel.Visible = myJobs.Count == 0;

        foreach (var job in myJobs)
        {
            var listing = new NanoGigsListingControl(job, state.ViewerAccountId, NanoGigsListingMode.MyJobs);
            listing.OnFinish += id => OnFinishJob?.Invoke(id);
            listing.OnCancel += id => OnCancelJob?.Invoke(id);
            MyJobsContainer.AddChild(listing);
        }
    }
}
