// SPDX-FileCopyrightText: 2025 Capibara Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Capibara.NanoGigs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Capibara.NanoGigs;

[GenerateTypedNameReferences]
public sealed partial class NanoGigsUiFragment : BoxContainer
{
    public event Action<string, string, string, int>? OnPostJob;
    public event Action<int>? OnAcceptJob;
    public event Action<int>? OnFinishJob;
    public event Action<int>? OnCancelJob;
    public event Action? OnToggleAlerts;

    public NanoGigsUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        TabContainer.SetTabTitle(JobBoardTab, Loc.GetString("nanogigs-ui-tab-board"));
        TabContainer.SetTabTitle(MyJobsTab, Loc.GetString("nanogigs-ui-tab-myjobs"));
        TabContainer.SetTabTitle(PostJobTab, Loc.GetString("nanogigs-ui-tab-post"));

        PayInput.InitDefaultButtons();
        PayInput.IsValid = i => i >= 1;
        PayInput.Value = 50;

        PostButton.OnPressed += _ =>
        {
            var title = TitleInput.Text.Trim();
            var description = DescriptionInput.Text.Trim();
            var location = LocationInput.Text.Trim();
            var pay = PayInput.Value;

            // Client-side validation
            string? clientError = null;
            if (string.IsNullOrEmpty(title) || title.Length > MaxTitle)
                clientError = Loc.GetString("nanogigs-error-invalid-title");
            else if (description.Length > MaxDescription)
                clientError = Loc.GetString("nanogigs-error-invalid-description");
            else if (location.Length > MaxLocation)
                clientError = Loc.GetString("nanogigs-error-invalid-location");
            else if (pay <= 0)
                clientError = Loc.GetString("nanogigs-error-invalid-pay");

            if (clientError != null)
            {
                ShowPostResult(false, clientError);
                return;
            }

            _waitingForPostResult = true;
            OnPostJob?.Invoke(title, description, location, pay);
        };

        AbandonButton.OnPressed += _ =>
        {
            if (_activeJobId != null)
                OnCancelJob?.Invoke(_activeJobId.Value);
        };

        AlertsButton.OnToggled += _ => OnToggleAlerts?.Invoke();

        Tabs.OnTabChanged += tab =>
        {
            // Leaving Post Job tab while result is showing — reset to form
            if (tab != 2 && PostResultOverlay.Visible)
            {
                PostResultOverlay.Visible = false;
                PostFormContent.Visible = true;
            }
        };

        PostResultButton.OnPressed += _ =>
        {
            PostResultOverlay.Visible = false;
            PostFormContent.Visible = true;
            if (_lastPostSuccess)
                Tabs.CurrentTab = 1; // Go to My Jobs on success
        };

        // Character limits — clamp input and update counters
        TitleInput.OnTextChanged += _ => ClampAndCount(TitleInput, TitleCounter, MaxTitle);
        DescriptionInput.OnTextChanged += _ => ClampAndCount(DescriptionInput, DescriptionCounter, MaxDescription);
        LocationInput.OnTextChanged += _ => ClampAndCount(LocationInput, LocationCounter, MaxLocation);
        UpdateCounter(TitleCounter, 0, MaxTitle);
        UpdateCounter(DescriptionCounter, 0, MaxDescription);
        UpdateCounter(LocationCounter, 0, MaxLocation);
    }

    private const int MaxTitle = 50;
    private const int MaxDescription = 150;
    private const int MaxLocation = 50;

    private static void ClampAndCount(LineEdit input, Label counter, int max)
    {
        if (input.Text.Length > max)
        {
            input.Text = input.Text[..max];
            input.CursorPosition = max;
        }

        UpdateCounter(counter, input.Text.Length, max);
    }

    private static void UpdateCounter(Label counter, int len, int max)
    {
        counter.Text = $"{len}/{max}";
        counter.Modulate = len >= max ? Color.FromHex("#e93d58") : Color.FromHex("#888888");
    }

    private int? _activeJobId;
    private bool _waitingForPostResult;
    private bool _lastPostSuccess;

    public void UpdateState(NanoGigsUiState state)
    {
        // Balance + Alerts
        BalanceLabel.Text = Loc.GetString("nanogigs-ui-balance-value", ("balance", state.ViewerBalance));
        AlertsButton.Pressed = state.AlertsEnabled;
        AlertsLabel.Text = state.AlertsEnabled
            ? Loc.GetString("nanogigs-ui-alerts-on")
            : Loc.GetString("nanogigs-ui-alerts-off");
        AlertsLabel.Modulate = state.AlertsEnabled ? Color.FromHex("#3dd425") : Color.FromHex("#888888");

        // Post Job tab — show one of: NoIdOverlay, PostResultOverlay, PostFormContent
        if (!state.HasIdCard)
        {
            NoIdOverlay.Visible = true;
            PostFormContent.Visible = false;
            PostResultOverlay.Visible = false;
        }
        else if (_waitingForPostResult)
        {
            _waitingForPostResult = false;
            ShowPostResult(string.IsNullOrEmpty(state.ErrorMessage), state.ErrorMessage);
        }
        else
        {
            NoIdOverlay.Visible = false;
            PostFormContent.Visible = true;
            PostResultOverlay.Visible = false;
        }

        // Check if viewer has an active job as taker
        var activeJob = state.Jobs.Find(j =>
            j.Status == NanoGigStatus.Accepted && j.TakerAccountId == state.ViewerAccountId);

        _activeJobId = activeJob?.GigId;

        // Job Board tab: show active job view or browse view
        if (activeJob != null)
        {
            BrowseView.Visible = false;
            ActiveJobView.Visible = true;
            PopulateActiveJob(activeJob);
        }
        else
        {
            BrowseView.Visible = true;
            ActiveJobView.Visible = false;
            PopulateJobBoard(state);
        }

        // My Jobs tab
        PopulateMyJobs(state);
    }

    private void ShowPostResult(bool success, string? errorMessage = null)
    {
        if (success)
        {
            _lastPostSuccess = true;
            TitleInput.Text = "";
            DescriptionInput.Text = "";
            LocationInput.Text = "";
            PayInput.Value = 50;
            UpdateCounter(TitleCounter, 0, MaxTitle);
            UpdateCounter(DescriptionCounter, 0, MaxDescription);
            UpdateCounter(LocationCounter, 0, MaxLocation);

            PostResultLabel.Text = Loc.GetString("nanogigs-ui-post-success");
            PostResultLabel.Modulate = Color.FromHex("#3dd425");
            PostResultButton.Text = Loc.GetString("nanogigs-ui-post-success-dismiss");
        }
        else
        {
            _lastPostSuccess = false;
            PostResultLabel.Text = errorMessage ?? "";
            PostResultLabel.Modulate = Color.FromHex("#e93d58");
            PostResultButton.Text = Loc.GetString("nanogigs-ui-error-dismiss");
        }

        NoIdOverlay.Visible = false;
        PostFormContent.Visible = false;
        PostResultOverlay.Visible = true;
        Tabs.CurrentTab = 2;
    }

    private void PopulateActiveJob(NanoGigListing job)
    {
        ActiveJobTitle.SetMessage(FormattedMessage.FromUnformatted(job.Title));
        ActiveJobDescription.SetMessage(FormattedMessage.FromUnformatted(
            string.IsNullOrEmpty(job.Description)
                ? Loc.GetString("nanogigs-ui-no-description")
                : job.Description));
        ActiveJobLocation.SetMessage(FormattedMessage.FromUnformatted(
            string.IsNullOrEmpty(job.Location)
                ? ""
                : Loc.GetString("nanogigs-ui-location", ("location", job.Location))));
        ActiveJobPoster.SetMessage(FormattedMessage.FromUnformatted(
            Loc.GetString("nanogigs-ui-posted-by", ("name", job.PosterName))));
        ActiveJobPay.Text = Loc.GetString("nanogigs-ui-pay-amount", ("pay", job.Pay));
        ActiveJobPay.Modulate = Color.FromHex("#3dd425");
    }

    private void PopulateJobBoard(NanoGigsUiState state)
    {
        JobListContainer.RemoveAllChildren();

        var availableJobs = state.Jobs.FindAll(j => j.Status == NanoGigStatus.Available);
        EmptyBoardLabel.Visible = availableJobs.Count == 0;

        foreach (var job in availableJobs)
        {
            var listing = new NanoGigsListingControl(job, state.ViewerAccountId, NanoGigsListingMode.Board);
            listing.OnAccept += id => OnAcceptJob?.Invoke(id);
            JobListContainer.AddChild(listing);
        }
    }

    private void PopulateMyJobs(NanoGigsUiState state)
    {
        MyJobsContainer.RemoveAllChildren();

        var myJobs = state.Jobs.FindAll(j => j.PosterAccountId == state.ViewerAccountId);
        EmptyMyJobsLabel.Visible = myJobs.Count == 0;

        foreach (var job in myJobs)
        {
            var listing = new NanoGigsListingControl(job, state.ViewerAccountId, NanoGigsListingMode.MyJobs);
            listing.OnFinish += id => OnFinishJob?.Invoke(id);
            listing.OnCancel += id => OnCancelJob?.Invoke(id);
            MyJobsContainer.AddChild(listing);
        }
    }
}
