// SPDX-FileCopyrightText: 2025 Capibara Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Capibara.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Capibara.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class CapibaraATMWindow : FancyWindow
{
    public event Action<int>? OnWithdraw;
    public event Action? OnDeposit;
    public event Action? OnInsert;
    public event Action? OnEject;
    public event Action? OnCreateAccount;

    public CapibaraATMWindow()
    {
        RobustXamlLoader.Load(this);

        WithdrawButton.OnPressed += _ => TryWithdraw();
        DepositButton.OnPressed += _ => OnDeposit?.Invoke();
        InsertButton.OnPressed += _ => OnInsert?.Invoke();
        EjectButton.OnPressed += _ => OnEject?.Invoke();
        CreateAccountButton.OnPressed += _ => OnCreateAccount?.Invoke();

        Btn50.OnPressed += _ => SetAmount(50);
        Btn100.OnPressed += _ => SetAmount(100);
        Btn200.OnPressed += _ => SetAmount(200);
        Btn500.OnPressed += _ => SetAmount(500);
    }

    public void UpdateState(CapibaraATMState state)
    {
        if (!state.HasIdInserted)
            AccountLabel.Text = Loc.GetString("capibara-atm-no-id");
        else
            AccountLabel.Text = state.AccountName ?? "";
        BalanceLabel.Text = $"{state.Balance} Sp";

        // Toggle Insert/Eject button visibility
        InsertButton.Visible = !state.HasIdInserted;
        EjectButton.Visible = state.HasIdInserted;

        // Show create account UI when card has no bank account
        CreateAccountButton.Visible = state.HasIdButNoAccount;
        NoAccountLabel.Visible = state.HasIdButNoAccount;

        // Disable operations when no ID is inserted or account not found
        WithdrawButton.Disabled = !state.Enabled;
        DepositButton.Disabled = !state.Enabled;
        AmountInput.Editable = state.Enabled;

        foreach (var btn in new[] { Btn50, Btn100, Btn200, Btn500 })
        {
            btn.Disabled = !state.Enabled;
        }
    }

    private void SetAmount(int amount)
    {
        AmountInput.Text = amount.ToString();
    }

    private void TryWithdraw()
    {
        if (int.TryParse(AmountInput.Text, out var amount) && amount > 0)
        {
            OnWithdraw?.Invoke(amount);
        }
    }
}
